In [2]:
import numpy as np
import pandas as pd

In [7]:
#load data 以文本形式读入，对于不同的数据类型要做处理
#datademographic_array = np.loadtxt('files/demographics.csv') # First attempt to load data
datademographic_array = np.loadtxt('files/demographics.csv',skiprows=1, delimiter=',', dtype= 'int64') # Success!
datademographic_array

array([[     1,      1,      0,     41,  40367,      0],
       [     2,      1,      0,     54,  45084,      0],
       [     3,      1,      0,     42,  52483,      0],
       ...,
       [149998,      7,      0,     26, 111885,      0],
       [149999,      7,      0,     25, 111878,      0],
       [150000,      7,      1,     37,  87251,      0]], dtype=int64)

In [8]:
# load data
datademographic = pd.read_csv('files/demographics.csv') # First attempt to load data
datademographic.head()

ID  City  Gender  Age  Income  Illness
0   1     1       0   41   40367        0
1   2     1       0   54   45084        0
2   3     1       0   42   52483        0
3   4     1       0   40   40941        0
4   5     1       0   46   50289        0

In [9]:
print(datademographic.shape)
print(datademographic.size)

(150000, 6)
900000


In [17]:
for col in datademographic.columns:
    print(col, "\n", datademographic.loc[:,col].size, "\n", datademographic.loc[:,col].value_counts(),  "\n\n\n", sep = "")

ID
150000
1         1
100013    1
99997     1
99998     1
99999     1
         ..
50001     1
50002     1
50003     1
50004     1
150000    1
Name: ID, Length: 150000, dtype: int64



City
150000
2    50307
3    32173
1    19707
4    14219
7    12292
5     8301
6     8120
8     4881
Name: City, dtype: int64



Gender
150000
0    83800
1    66200
Name: Gender, dtype: int64



Age
150000
26    3918
64    3879
43    3862
41    3862
54    3838
29    3805
28    3798
27    3790
63    3784
44    3782
36    3780
59    3775
47    3773
37    3771
33    3769
58    3762
49    3762
42    3760
32    3759
52    3753
31    3749
48    3743
40    3740
61    3737
38    3734
57    3732
30    3731
51    3729
53    3724
34    3710
46    3707
50    3692
55    3687
62    3684
39    3675
45    3670
35    3658
56    3602
60    3582
25    1868
65    1864
Name: Age, dtype: int64



Income
150000
98410     15
93808     13
94606     13
88730     12
96376     12
          ..
91227      1
119770     1
81621      1
11

In [23]:
np.unique(datademographic_array[:,1], return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),
 array([19707, 50307, 32173, 14219,  8301,  8120, 12292,  4881],
       dtype=int64))

In [24]:
categories, counts = np.unique(datademographic_array[:,1], return_counts=True)
categories,counts

(array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),
 array([19707, 50307, 32173, 14219,  8301,  8120, 12292,  4881],
       dtype=int64))

In [22]:
for col in range(datademographic_array.shape[1]):
    print(col, np.unique(datademographic_array[:,col]).size, np.unique(datademographic_array[:,col], return_counts = True), "\n")

0 150000 (array([     1,      2,      3, ..., 149998, 149999, 150000], dtype=int64), array([1, 1, 1, ..., 1, 1, 1], dtype=int64)) 

1 8 (array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64), array([19707, 50307, 32173, 14219,  8301,  8120, 12292,  4881],
      dtype=int64)) 

2 2 (array([0, 1], dtype=int64), array([83800, 66200], dtype=int64)) 

3 41 (array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65], dtype=int64), array([1868, 3918, 3790, 3798, 3805, 3731, 3749, 3759, 3769, 3710, 3658,
       3780, 3771, 3734, 3675, 3740, 3862, 3760, 3862, 3782, 3670, 3707,
       3773, 3743, 3762, 3692, 3729, 3753, 3724, 3838, 3687, 3602, 3732,
       3762, 3775, 3582, 3737, 3684, 3784, 3879, 1864], dtype=int64)) 

4 71762 (array([        -654,          584,         2474, ..., 415240000000,
       500820000000, 547770000000], dtype=int64), array([1, 1, 1, ..., 1, 1, 1], dtype

 随机抽取数字组成数组 numpy.random.choice(a, size=None, replace=True, p=None)
    从a(只要是ndarray都可以，但必须是一维的)中随机抽取数字，并组成指定大小(size)的数组
    replace:True表示可以取相同数字，False表示不可以取相同数字
    数组p：与数组a相对应，表示取数组a中每个元素的概率，默认为选取每个元素的概率相同。