In [15]:
import numpy as np
import random

In [8]:
# 使用numpy生成数组，得到ndarray的数据类型
t1 = np.array([1,2,3,])
print(t1)
print(type(t1))   #该数组的类型

t2 = np.array(range(10))
print(t2)

t3 = np.arange(4,10,2)   # start, end, step
print(t3)
print(t3.dtype)  # 数据的类型

[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[4 6 8]
int32


In [14]:
# 指定数据类型
t4 = np.array(range(1,4),dtype = float)
print(t4)
print(t4.dtype)

#bool类型
t5 = np.array([1,1,0,1,0,0],dtype = bool)
print(t5)
print(t5.dtype)

# 调整数据类型
t6 = t5.astype("int8")
print(t6)
print(t6.dtype)

[1. 2. 3.]
float64
[ True  True False  True False False]
bool
[1 1 0 1 0 0]
int8


In [20]:
#小数
t7 = np.array([random.random() for i in range(10)])
print(t7)
print(t7.dtype)

# 保留小数位数 np.round(b,x)
t8 = np.round(t7,3)
print(t8)

# 另一种保留小数的办法：
print("%.2f"%random.random())

[0.10513667 0.18570536 0.34259343 0.40071156 0.11772398 0.03529579
 0.36820857 0.54274247 0.92622186 0.33598915]
float64
[0.105 0.186 0.343 0.401 0.118 0.035 0.368 0.543 0.926 0.336]
0.95


In [33]:
#数组的形状
a1 = np.arange(12)
print(a1)
print(a1.shape)

a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [49]:
# 修改数组形状：二维数据
s1 = a1.reshape((3,4))
print(s1)
print("-------------")
# 三维数据
a3 = np.arange(24)
print(a3.reshape((2,3,4)))# block,roll,column
print("-------------")
print(a3.reshape((4,6)))
print("-------------")
# reshape有返回值，不改变本身的值
# 修改值则要重新赋值
a3 = a3.reshape((4,6))

# 重新变回一维数组
print(a3.reshape((24,)))
print("-------------")
# 注意这个仍为二维数组
print(a3.reshape((1,24)))
print("-------------")

# 未知数据个数时变为一维数组
# 方法一：采用reshape函数
a4 = a3.reshape((a3.shape[0]*a3.shape[1],))  #shape[0]为行数，shape[1]为列数，两个相乘即得元素个数
print(a4)
print("-------------")
# 方法二: 采用flatten()函数
print(a3.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
-------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
-------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
-------------
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
-------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
-------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [66]:
#数组的计算
# 广播机制
print(a3)
print("-------------")
print(a3+2)
print("-------------")
print(a3/2)
print("-------------")
print(a3/0)
print("-------------")

#相同shape的计算
a5 = np.arange(10,34).reshape((4,6))
print(a5)
print(a5+a3)
print(a5*a3)
print("-------------")


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
-------------
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]]
-------------
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
-------------
[[nan inf inf inf inf inf]
 [inf inf inf inf inf inf]
 [inf inf inf inf inf inf]
 [inf inf inf inf inf inf]]
-------------
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]
[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]]
[[  0  11  24  39  56  75]
 [ 96 119 144 171 200 231]
 [264 299 336 375 416 459]
 [504 551 600 651 704 759]]
-------------


C:\Windows\Temp\ipykernel_24952\3454063287.py:8: RuntimeWarning: divide by zero encountered in true_divide
  print(a3/0)
C:\Windows\Temp\ipykernel_24952\3454063287.py:8: RuntimeWarning: invalid value encountered in true_divide
  print(a3/0)


In [67]:
#不同shape

#在行的维度上相同，在每一行上进行加减运算
a6 = np.arange(0,6)
print(a3-a6)
print("-------------")

# 在列的维度上相同,
a7 = np.arange(4).reshape((4,1))
print(a7)
print(a3-a7)

#其他情况下无法计算

[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]
-------------
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]
